// 文件说明：封装所有前端调用的接口方法，页面只需要按业务名称调用即可。
import http from './http';

export const api = {
  register: (payload) => http.post('/auth/register', payload),
  login: (payload) => http.post('/auth/login', payload),
  me: () => http.get('/auth/me'),
  updateAdminProfile: (payload) => http.put('/auth/admin-profile', payload),
  logout: () => http.post('/auth/logout'),
  books: (params) => http.get('/books', { params }),
  bookDetail: (id) => http.get(`/books/${id}`),
  createBook: (payload) => http.post('/books', payload),
  updateBook: (id, payload) => http.put(`/books/${id}`, payload),
  updateBookStatus: (id, payload) => http.patch(`/books/${id}/status`, payload),
  categories: () => http.get('/categories'),
  createCategory: (payload) => http.post('/categories', payload),
  updateCategory: (id, payload) => http.put(`/categories/${id}`, payload),
  deleteCategory: (id) => http.delete(`/categories/${id}`),
  cart: () => http.get('/cart'),
  addCart: (payload) => http.post('/cart', payload),
  updateCart: (id, payload) => http.put(`/cart/${id}`, payload),
  deleteCart: (id) => http.delete(`/cart/${id}`),
  clearCart: () => http.delete('/cart'),
  createOrder: (payload) => http.post('/orders', payload),
  myOrders: () => http.get('/orders/my'),
  myOrderDetail: (id) => http.get(`/orders/my/${id}`),
  adminOrders: (params) => http.get('/orders', { params }),
  adminOrderDetail: (id) => http.get(`/orders/${id}`),
  shipOrder: (id) => http.patch(`/orders/${id}/ship`),
  users: () => http.get('/users'),
  userDetail: (id) => http.get(`/users/${id}`),
  updateUser: (id, payload) => http.put(`/users/${id}`, payload),
  statsOverview: () => http.get('/stats/overview'),
  statsTrend: (params) => http.get('/stats/sales-trend', { params }),
  statsTopBooks: (params) => http.get('/stats/top-books', { params }),
  statsCategoryShare: (params) => http.get('/stats/category-share', { params }),
  statsLowStock: () => http.get('/stats/low-stock'),
  statsExport: (params) => http.get('/stats/export', { params, responseType: 'blob' })
};
